%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\xvever12\Desktop\MKS\MKS\Lecture 6\ntc.csv
%
% Auto-generated by MATLAB on 02-Nov-2023 16:00:03

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["t", "resistance"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
ntc = readtable("C:\Users\xvever12\Desktop\MKS\MKS\Lecture 6\ntc.csv", opts);

t = ntc.t;
r = ntc.resistance;

ad = (r ./ (r + 10)) * 2^10;

p = polyfit(ad, t, 10);
ad2 = 0:1023;
t2 = round(polyval(p, ad2), 1);
dlmwrite('data.dlm', t2*10, ',');

figure;
plot(ad, t, 'bo');
hold on, 
plot(ad2, t2, 'r');

%% Clear temporary variables
clear opts